name = "expaccess"
main = "worker.js"
compatibility_date = "2026-02-15"

[[kv_namespaces]]
binding = "ACCESS_KV"
id = "cef47031bb6f48e1b1d7aab33370dfdc"
# preview_id = "<PASTE_ACCESS_KV_PREVIEW_ID>"

[[r2_buckets]]
binding = "ASSETS_R2"
bucket_name = "exp-assets"

[[r2_buckets]]
binding = "PSYCHOJS_R2"
bucket_name = "exp-psychojs-lib"

[[r2_buckets]]
binding = "DATA_R2"
bucket_name = "exp-data"